#! /usr/bin/env bash
# fname: gupdate-file-en
# 20260313 v1  en
# last: 20260313
# ---

HST="en"
SRCDIR=$PWD

if [[ ! "${SRCDIR}" =~ "majstaf" ]]; then
	printf "[ERROR] not working outside ~/majstaf/\n"
	printf "\n"
	exit
fi

if [[ $# -ne 1 ]]; then
	cat <<EOF
	Usage: gupdate-file ./<fname>

EOF
	exit
else
	fname="$1"
fi

if [[ ! -f ./"${fname}" ]]; then
	echo "[ERROR] no such file"
	exit
fi

SRCF="${SRCDIR}/${fname}"
DSTF=$(echo $SRCDIR/${fname} | sed "s/\(.*majstaf\)\/\([[:alpha:]]\+\)\/\(.*\)/\1\/engit\/\2_en\/\3/")

update_file_to_git() {
	printf "%s\n%s\n%s\n" \
		"from: ${SRCF}" \
		"to:   ${DSTF}" \
		"---"
	cp -iv "${SRCF}" "${DSTF}"
}

# MAIN
update_file_to_git

printf "\n"
