#! /usr/bin/env bash

# jbegit-multiple-repos-setup.sh
# 20250430
# -------------------

# globals
hst="jbe"
gh_clone_addr="https://github.com/r-gregor"
gl_clone_addr="https://gitlab.com/r-gregor"

gh_rmt_addr="git@github.com:r-gregor"
gl_rmt_addr="git@gitlab.com:r-gregor"

# single repo clone and setup function
single_repo_setup() {
	if [ $# -ne 1 ]; then
		echo [ERROR] "must supply repo name as argument"
		exit
	else
		repo=$1
	fi

	repo_name=${repo}_${hst}
	
	echo "[INFO] setup git repository for ${repo_name} ..."
	read -p "Continue?"

	echo "[INFO] cloning/setting up repository: ${repo_name}"
	git clone ${gh_clone_addr}/${repo_name}.git
	cd ${repo}_${hst}

	git branch -m main
	git remote add gh_${repo_name} ${gh_rmt_addr}/${repo_name}.git
	git remote add gl_${repo_name} ${gl_rmt_addr}/${repo_name}.git
	git remote rm origin
	git remote -v

	git pull gh_${repo_name} main --set-upstream
	cd ../
}

for repo in majbin majrcs metsys; do
	single_repo_setup ${repo}
done

echo "[INFO] done"

