#! /usr/bin/env bash
# filename: majapps-launch
# 20250917 (d)
# 20251020 (d) -- run inside infinite loop and added 'q' to quit
#              -- keys in separate index-ed array to keep display order
# last: 20251020 (d)

declare -A apps=(["Firefox"]="/usr/bin/firefox" \
                 ["Google Chrome"]="/usr/bin/google-chrome" \
                 ["Mate calculator"]="/usr/bin/mate-calculator" \
                 ["Mousepad"]="/usr/bin/mousepad" \
                 ["Thunar FM"]="/usr/bin/thunar" \
                 # ["Double Commander"]="/usr/bin/doublecmd" \
                 ["Transmission"]="/usr/bin/transmission-gtk" \
                 ["ArandR"]="/usr/bin/arandr" \
                 ["VLC"]="/usr/bin/vlc")

declare -a keys=("Firefox" \
	             "Google Chrome" \
				 "Mate calculator" \
				 "Mousepad" \
				 "Thunar FM" \
				 # "Double Commander" \
                 "Transmission" \
				 "ArandR" \
				 "VLC" \
				 "q (quit)")

while true; do

	selection=$(for key in "${!keys[@]}"; do echo "${keys[$key]}"; done | \
				fzf \
				--reverse \
				--border=rounded \
				--info=hidden \
				--height=15 \
				+c \
				--prompt="launch: ")

	if [ "x${selection}" == "x" ]; then
		echo "[ERROR] no aplication selected"
		exit
	fi

		# RUN
		if [ "${selection}" == "q (quit)" ]; then
			exit
		fi

		eval "nohup ${apps["${selection}"]} >&/dev/null &"

done

