#! /usr/bin/env bash
# filename: majapps-launch
# 20250917 (d)
# 20251020 (d) -- run inside infinite loop and added 'q' to quit
#              -- keys in separate index-ed array to keep display order
# last: 20251020 (d)

# clear the screen:
printf "\033[H\033[2J"

declare -A apps=(["Firefox"]="/usr/bin/firefox" \
                 ["ArandR"]="/usr/bin/arandr" \
                 ["Atril"]="/usr/bin/atril" \
                 ["Gimp"]="/usr/bin/gimp" \
                 ["Google Chrome"]="/usr/bin/google-chrome" \
                 ["Gparted"]="/usr/sbin/gparted" \
                 ["Kitty"]="/usr/bin/kitty" \
                 ["KODI"]="/usr/bin/kodi" \
                 ["LxAppearance"]="/usr/bin/lxappearance" \
                 ["LxTask"]="/usr/bin/lxtask" \
                 ["Mate calculator"]="/usr/bin/mate-calculator" \
                 ["Mousepad"]="/usr/bin/mousepad" \
                 ["Nitrogen"]="/usr/bin/nitrogen" \
                 ["PavucControl"]="/usr/bin/pavucontrol" \
                 ["PCmanFM"]="/usr/bin/pcmanfm" \
                 ["Pinta"]="/usr/bin/pinta" \
                 ["Thunar FM"]="/usr/bin/thunar" \
                 ["Transmission"]="/usr/bin/transmission-gtk" \
                 ["Ulauncher"]="/usr/bin/ulauncher" \
                 ["VLC"]="/usr/bin/vlc" \
                 ["Xsane"]="/usr/bin/xsane" \
                 ["q (quit)"]="")

declare -a keys=("Firefox" \
                 "ArandR" \
                 "Atril" \
                 "Gimp" \
                 "Google Chrome" \
                 "Gparted" \
                 "Kitty" \
                 "KODI" \
                 "LxAppearance" \
                 "LxTask" \
                 "Mate calculator" \
                 "Mousepad" \
                 "Nitrogen" \
                 "PavucControl" \
                 "PCmanFM" \
                 "Pinta" \
                 "Thunar FM" \
                 "Transmission" \
                 "Ulauncher" \
                 "VLC" \
                 "Xsane" \
                 "q (quit)")

while true; do

	# add +c option to reverse highlight
	selection=$(for key in "${!keys[@]}"; do echo "${keys[$key]}"; done | \
				fzf -e \
				--reverse \
				--border=rounded \
				--info=hidden \
				--height=25 \
				--prompt="launch (q to quit): ")

	if [ "x${selection}" == "x" ]; then
		echo -e "[ERROR] no aplication selected\n"
		exit
	fi

		# RUN
		if [ "${selection}" == "q (quit)" ]; then
			exit
		fi

		eval "nohup ${apps["${selection}"]} >&/dev/null &"

done

