#! /usr/bin/env bash

# STRUCTURE:
# $HOME/
#	/dev/
#		/my-prog/
#				/src/
#					/include/
#							/my-prog.h
#					/my-prog.cpp
#				/build-debug/
#							/src/
#									/my-prog
#				/build-release/
#								/src/
#									/my-prog
#				/Makefile

# RUT=${HOME}
RUT="."
project_name=default
prefix="$RUT/majstaf/dev"
project_path=${prefix}/${project_name}

echo "Creating new project: ${project_name}"

mkdir -vp ${project_path}/{src,lib,include,tests,bin,build}

tree ${project_path}



