#! /usr/bin/env bash
# filename: majapps-launch.sh
# 20250917 en
# 20250919 en v1 added runff var for firefox path
# 20251017 en v2 run inside infinite loop and added 'q' to quit
#                keys in separate index-ed array to keep display order
# 20260317 en v3 $delline calculated from longest KEY line with get_longest function
#                sorted output to fzf command
#                extract KEYS from URLS
# last: 20260317
# ---

runff="/c/Users/gregor.redelonghi/majstaf_en/majprogs_en/FireFox_63.0.1/FirefoxPortable.exe"

# gr_MSE=/c/Program\ Files\ \(x86\)/Microsoft/Edge/Application/msedge.exe
runedg="/c/Program Files (x86)/Microsoft/Edge/Application/msedge.exe"

declare -A apps=(["Firefox"]="/c/Users/gregor.redelonghi/majstaf_en/majprogs_en/FireFox_63.0.1/FirefoxPortable.exe" \
                 ["MS Edge"]="$(cygpath -w /c/Program\ Files\ \(x86\)/Microsoft/Edge/Application/msedge.exe)" \
                 ["Google Chrome"]="C:\Program Files\Google Chrome Portable\GoogleChromePortable.exe" \
                 ["MS Calc"]="/c/Windows/System32/calc.exe" \
                 ["Acrobat Reader"]="C:\Program Files (x86)\Adobe\Acrobat Reader DC\Reader\AcroRd32.exe"
                 ["AutoCAD 2024"]=""
                 ["Explorer++"]="/c/Users/gregor.redelonghi/majstaf_en/majprogs_en/Explorerpp/Explorer++.exe" \
                 ["Notepad++"]="/c/Users/gregor.redelonghi/majstaf_en/majprogs_en/Notepad++/notepad++.exe" \
                 ["MultiCommander"]="/c/Users/gregor.redelonghi/majstaf_en/majprogs_en/MultiCommander_X64/MultiCommander.exe"
                 ["Super Launcher"]="c:\Users\Public\below average\Super Launcher\SuperLauncher.exe" \
                 ["Nukleus (EN)"]="" \
                 ["URE"]="" \
                 ["Razvojne Rešitve (EN)"]="")

# array of keys from apps
keys=("${!apps[@]}") # v3

# functions #v3
get_longest() {
	if [ ! $# -eq 1 ]; then
		echo "[ERROR1] must supply array of sentences as parameter"
		exit 1
	fi

	local len=0
	local longest
	local -n lines2=$1 # new way: must call array as < array_name >

	for line in "${lines2[@]}"; do
		llen="${#line}"
		if [ "${llen}" -gt "${len}" ]; then
			len="${llen}"
			longest="${line}"
		else
			continue
		fi
	done

	echo "${longest}"
}

# MAIN # v3
longest_l=$(get_longest keys)                                         # v3
delline=$(for((i = 0; i < ${#longest_l}; i++)); do printf "-"; done)  # v3

while true; do
	selection=$((for key in "${!keys[@]}"; do echo "${keys[$key]}"; done | sort; echo "${delline}"; echo "Quit") | \
		fzf \
		-e \
		--reverse \
		-i \
		--prompt="launch: ")

	if [ "x${selection}" == "x" ]; then
		echo -e "[INFO] no selection\n"
		exit
	fi

	if [ "${selection}" == "${delline}" ]; then #v3
		continue
	fi

# RUN
	if [ "${selection}" == "AutoCAD 2024" ]; then
		cygstart "C:\Program Files\Autodesk\AutoCAD 2024\acad.exe"  /product ACAD /language "en-US" &>/dev/null
	elif [ "${selection}" == "Nukleus (EN)" ]; then
		${runff} "http://jpe-nukleus.jhl.si/PassAuth/AutoAuth.aspx?ReturnUrl=/nukleus/profile.aspx?id=Energetika@Ljubljana"
	elif [ "${selection}" == "Razvojne Rešitve (EN)" ]; then
		${runff} "https://jpe-arcgis-port.jhl.si/arcgis/apps/webappviewer/index.html?id=b7ec743d0247439fbe941cb6187fa094"
	elif [ "${selection}" == "URE" ]; then
		jhl_ure="https://ris.jhl.si/"
		# cygstart "${runedg}" ${jhl_ure}
		"${runedg}" ${jhl_ure}
	elif [ "${selection}" == "Quit" ]; then # v3
		exit
	else
		cygstart "${apps["${selection}"]}" &>/dev/null
	fi
	clear
done

#############################################
# TODO
# gr_verzija=" [ verzija-en - last update: 202401119 ] "
# gr_izbira=""
# gr_OFPOT='/c/Program Files/Microsoft Office/root/Office16'
# gr_GGL="/c/Users/gregor.redelonghi/AppData/Local/Google/Chrome/Application/chrome.exe"
# gr_FF=/c/Users/gregor.redelonghi/majstaf_en/majprogs_en/FireFox_63.0.1/FirefoxPortable.exe
# gr_MSE=/c/Program\ Files\ \(x86\)/Microsoft/Edge/Application/msedge.exe
# ------------------------------------------------------------------------------------------
# cygstart "${gr_OFPOT}/EXCEL.EXE"
# cygstart "${gr_OFPOT}/WINWORD.EXE"
# cygstart "${gr_OFPOT}/POWERPNT.EXE"
# cygstart "${gr_OFPOT}/OUTLOOK.EXE"
# cygstart explorer /E,"$(cygpath -w /c/users/gregor.redelonghi/${CURRYR})"
# cygstart /c/WINDOWS/system32/ssmypics.scr /s
# cygstart /c/users/gregor.redelonghi/majstaf_en/majprogs_en/cygwin64/bin/mintty.exe -p 40,40 -s 200,50 -
# cygstart /c/Users/gregor.redelonghi/majstaf_en/majprogs_en/CodeBlocks/codeblocks.exe
# cygstart /c/WINDOWS/System32/rundll32.exe user32.dll LockWorkStation
# cygstart /c/WINDOWS/System32/rundll32.exe  shell32.dll,Control_RunDLL hotplug.dll
#############################################

