#! /usr/bin/env bash

if [ $# -ne 1 ]; then
	printf "[ERROR] must supply a fiename as parameter\n\n"
	exit
else
	fname=$1
fi

if [ ! -f ${fname} ]; then
	printf "[ERROR] no such file: ${fname}\n\n"
	exit
fi

LINE='for FJL in $(echo ${fjls[@]}); do echo "$FJL"; done | tee /dev/tty | xargs -ro vim -pMi'
sed -e "/Selected/,\$s%^%# %" -e "\$s%.*%${LINE}%" -e "/Selected/s%^# %%" ${fname}
