#! /usr/bin/env bash
# filename: kndb-files-from-yr-tmst-in-mnth-mdb
# 20260104
# last: 20260104
# ---

curryr=$(date +"%Y")
currmn=$(date +"%m")
currdy=$(date +"%d")

scrpt=$(basename $0)
SRCDIR=${KNOWLEDGEDB:-/home/rgregor/majstaf/mdbgit/knowledgedb}

months=("" "January" "February" "March" "April" "May" "June" "July" "Avgust" "September" "October" "November" "December")
month_days=(0 31 29 31 30 31 30 31 31 30 31 30 31)

usage() {
cat << EOF
    Usage: ${scrpt} + 3 parameters:
                      <year>
                      <month_num>
                      <day_num>

       or: ${scrpt} + 2 parameters:
                      <month_num>
                      <day_num>
                      (year is current year)

EOF
}

if [ $# -eq 2 ]; then
	curryr=$(date +%Y)
	mnth=$1
	day=$2
elif [ $# -eq 3 ]; then
	curryr=$1
	mnth=$2
	day=$3
else
	usage
	exit
fi


# if [ $# -ne 3 ]; then
# 	echo "Must supply exactly three parameters:"
# 	usage
# 	exit
# else
# 	year=$1
# 	mnth=$2
# 	day=$3
# fi

if [ ${mnth} -lt 1 ] || [ ${mnth} -gt 12 ]; then
	echo "Month out of range (1 - 12)"
	exit
elif [ ${day} -lt 1 ] || [ ${day} -gt 31 ]; then
	echo "Day of month out of range (1 - 31)"
	exit
elif [ ${mnth} -eq ${currmn} ] && [ ${day} -gt ${currdy} ]; then
	echo "Day of current month out of range"
	exit
fi

unset RESULT
# readarray -t RESULT < <(for DYS in $(seq ${day} ${month_days[${mnth}]}); do find ${SRCDIR} -iname "*${curryr}${mnth}${DYS}.txt"; done)
readarray -t RESULT < <(for DYS in $(seq ${day} ${month_days[${mnth}]}); do find ${SRCDIR} \
	-iname $(printf "*%d%02d%02d.txt" ${curryr} ${mnth} ${DYS}); done)

if [ "x${RESULT[0]}" == "x" ]; then
	echo -e "[INFO] No files found\n"
	exit
fi

unset fjls
readarray -t fjls < <(for FJL in $(echo ${RESULT[@]}); do echo "$FJL"; done | fzf -m -e --reverse)

if [ "x${fjls[0]}" == "x" ]; then
	echo -e "[INFO] No files selected\n"
	exit
fi

for FJL in $(echo ${fjls[@]}); do echo $FJL; done | xargs -ro vim -pM

