#! /usr/bin/env bash

# STRUCTURE:
#/my-git-prog/
#		/src/
#			/include/
#					/my-prog.h
#			/my-prog.cpp
#		/build-debug/
#					/src/
#							/my-prog
#		/build-release/
#						/src/
#							/my-prog
#		/Makefile

# RUT=${HOME}
project_path=$(basename ${PWD})

echo "Setting up git-project: ${PWD}"

mkdir -vp ./${project_path}/{src,lib,include,tests,bin,build}

tree ./${project_path}



