#! /usr/bin/env bash
# filrname: ff-launch--en
# 20251117 v1 en
# 20251117 v2 en: :associative array --> no case statement needed
# 20251117 v3 en: ALL --> cat all txt files into process subst ...
#                 no 'all.txt' needed
# 20251118 v4 en: single "sites.txt" with "[section name]" headers parsing
# 20251118 v5 en: get 'categories' from 'sites.txt' file directly
# last: 20251118 en

clear

# globals
FFCMD='/usr/bin/firefox'
SRCDIR="$(dirname $(realpath ${BASH_SOURCE[0]}))"
SITES="${SRCDIR}/sites.txt"
FZFCMD="fzf -e --reverse --height 50% --border rounded"

ff_launch() {
	if [ "$1" == "all" ]; then
		readarray -t URLS < <(cat ${SITES})
	else
		site=$1
		# v4
		# readarray -t URLS < <(sed -n "/\[${site}\]/,/^$/p" ${SITES} | sed -n '2,$'p)
		readarray -t URLS < <(sed -n "/\[${site}\]/,/^$/p" ${SITES})
	fi

	selection=$(for URL in "${URLS[@]}"; do echo "$URL"; done 2>/dev/null | ${FZFCMD})

	if [ "x${selection}" == "x" ]; then
		echo -e "[INFO] nothing selected\n"
		exit
	fi

	if [[ ${selection} =~ ^(---) ]]; then
		echo -e "[INFO] nothing selected\n"
		exit
	fi

	if [[ ${selection} =~ ^\[.*\] ]]; then
		echo -e "[INFO] nothing selected\n"
		exit
	fi

	path=$(echo "${selection}" | cut -d ' ' -f1)
	nohup ${FFCMD} "${path}" >&/dev/null &
}

# v5
readarray -t categories < <(sed -n "/\[.*\]/p" "${SITES}" | sed -e 's/\[//' -e 's/\]//')
categories+=("ALL")
categories+=("q (quit)")

selected=$(for WAY in "${categories[@]}"; do echo $WAY; done | fzf +c --reverse)

if [ "x${selected}" == "x" ]; then
	echo -e "[INFO] nothing selected\n"
	exit
fi

if [ "${selected}" == "q (quit)" ]; then
	exit
fi

if [ "${selected}" == "ALL" ]; then
	dest="all"
else
	dest="${selected}"
fi

ff_launch "${dest}"

