#! /usr/bin/env bash
# filename: copy-files-to-multiple-dirs
# 20260506 v1
# copy selected files to multiple directories. Add each file with optinon -f
# and each direcory with option -d
# last: 20260506
# ---

set -e

fjls=()
dsts=()
darg=false
farg=false

usage() {
cat <<USAGE

usage: copy-files-to-multiple-dirs -f <fname1> -f <fname2> -d <dirname1> -d <dirname2> ...
                              -h ... print this message

USAGE
}

OIFS=$IFS
IFS='\n'
while getopts "f:d:h" opt; do
	case $opt in
		f)
			fjls+=("$OPTARG")
			farg=true
			;;
		d)
			dsts+=("$OPTARG")
			darg=true
			;;
		h)
			usage
			exit
			;;
		*)
			usage
			exit
			;;
	esac
done

if [ "${farg}" != "true" ]; then
	echo "[ERROR] no file selected"
	usage
	exit
fi


if [ "${darg}" != "true" ]; then
	echo "[ERROR] no directory selected"
	usage
	exit
fi
IFS=$OIFS

for DDD in "${dsts[@]}"; do
	if [ ! -d "${DDD}" ]; then
		printf "[ERROR] no such directory: ${DDD}\n\n"
		exit
	fi
done

for FFF in "${fjls[@]}"; do
	if [ ! -f "${FFF}" ]; then
		printf "[ERROR] no such file: ${FFF}\n\n"
		exit
	fi
done

for DST in "${dsts[@]}"; do
	# printf "cp -vi ${fjls[*]} ${DST}\n"
	/usr/bin/cp -vi "${fjls[@]}" "${DST}"
done

