#! /usr/bin/env bash
# filrname: nested-ff-launch.sh
# 20251117 v1 en
# 20251117 v2 en:	associative array --> no case statement needed
# last: 20251117

clear

# globals
FFCMD=/c/Users/gregor.redelonghi/majstaf_en/majprogs_en/FireFox_63.0.1/FirefoxPortable.exe
SRCDIR="$(dirname $(realpath ${BASH_SOURCE[0]}))"

ff_launch() {
	local site=$1
	local SRC="$(dirname $(realpath ${BASH_SOURCE[0]}))/${site}"

	local URLs
	readarray -t URLS < <(cat ${SRC})
	local selection=$(for URL in "${URLS[@]}"; do echo "$URL"; done | fzf -e --reverse)

	if [ "x${selection}" == "x" ]; then
		echo -e "[INFO] nothing selected\n"
		exit
	fi

	if [[ ${selection} =~ ^(---) ]]; then
		echo -e "[INFO] nothing selected\n"
		exit
	fi

	local path=$(echo "${selection}" | cut -d ' ' -f1)
	cygstart ${FFCMD} "${path}"
}

# numers so it is sorted
declare -A directions=(["01 - c programming"]="cprogramming.txt" \
                       ["02 - programming portals"]="programmingportals.txt" \
                       ["03 - ytb channels"]="ytbchannels.txt" \
                       ["04 - ytb playlists"]="ytbplaylists.txt" \
                       ["05 - linux stuff"]="linuxstuff.txt"\
                       ["06 - technews.txt"]="technews.txt" \
                       ["07 - ALL"]="all.txt"
                       ["08 - q (quit)"]="")

selected=$(for WAY in "${!directions[@]}"; do echo $WAY; done | sort | fzf +c --reverse)

if [ "x${selected}" == "x" ]; then
	echo -e "[INFO] nothing selected\n"
	exit
fi

if [ "${selected}" == "08 - q (quit)" ]; then
	exit
fi

ff_launch ${directions[${selected}]}

