#! /usr/bin/env bash
# filename: kndb-files-from-tmst-in-mnth-en
# 20251125
# last: 20251125
# ---

curryr=$(date +"%Y")
currmn=$(date +"%m")
currdy=$(date +"%d")

scrpt=$(basename $0)
SRCDIR=${KNOWLEDGEDB:-/home/gregor.redelonghi/majstaf/engit/knowledgedb}

months=("" "January" "February" "March" "April" "May" "June" "July" "Avgust" "September" "October" "November" "December")
month_days=(0 31 29 31 30 31 30 31 31 30 31 30 31)

usage() {
cat << EOF
	Usage: ${scrpt} <month_num> <day_num>
	
EOF
}

if [ $# -ne 2 ]; then
	echo "Must supply exactly two parameters:"
	usage
	exit
else
	mnth=$1
	day=$2
fi

if [ ${mnth} -lt 1 ] || [ ${mnth} -gt 12 ]; then
	echo "Month out of range (1 - 12)"
	exit
elif [ ${day} -lt 1 ] || [ ${day} -gt 31 ]; then
	echo "Day of month out of range (1 - 31)"
	exit
elif [ ${mnth} -eq ${currmn} ] && [ ${day} -gt ${currdy} ]; then
	echo "Day of current month out of range"
	exit
fi

unset RESULT
# readarray -t RESULT < <(for DYS in $(seq ${day} ${month_days[${mnth}]}); do find ${SRCDIR} -iname "*${curryr}${mnth}${DYS}.txt"; done)
readarray -t RESULT < <(for DYS in $(seq ${day} ${month_days[${mnth}]}); do find ${SRCDIR} \
	-iname $(printf "*%d%02d%02d.txt" ${curryr} ${mnth} ${DYS}); done)

if [ "x${RESULT[0]}" == "x" ]; then
	echo -e "[INFO] No files found\n"
	exit
fi

unset fjls
readarray -t fjls < <(for FJL in $(echo ${RESULT[@]}); do echo "$FJL"; done | fzf -m -e --reverse)

if [ "x${fjls[0]}" == "x" ]; then
	echo -e "[INFO] No files selected\n"
	exit
fi

for FJL in $(echo ${fjls[@]}); do echo $FJL; done | xargs -ro vim -pM

