#! /usr/bin/env bash

gDest="/media/rgregor/EKSFAT/backup_jbez0rg"

sudo rsync -rtLDv --delete --progress \
	--exclude SLIKE/ \
	--exclude=".cache/" \
	--exclude=".thumbnails/" \
	--exclude="majstaf/majmedia/Movies" \
	/home/ ${gDest}/home/

