#! /usr/bin/env bash
# filenme: ff-launch-jbe
# 20250605 v2 en
# 20250605 v3 d

CMD='/usr/bin/firefox'
SRC="$(dirname $(realpath ${BASH_SOURCE[0]}))/sites.txt"

readarray -t URLS < <(cat ${SRC})
selection=$(for URL in "${URLS[@]}"; do echo "$URL"; done | fzf -e --reverse --height 50% --border rounded)

if [ "x${selection}" == "x" ]; then
	echo "[ERROR] nothing selected"
	exit
fi

path=$(echo "${selection}" | cut -d ' ' -f1)
nohup $CMD "${path}" >&/dev/null &

