#! /usr/bin/env bash
# filenme: ff-launch-mdb
# 20250605 v2 en
# 20250605 v3 d

# CMD=/c/Users/gregor.redelonghi/majstaf_en/majprogs_en/FireFox_63.0.1/FirefoxPortable.exe
CMD='/usr/bin/firefox'

SRC="$(dirname $(realpath ${BASH_SOURCE[0]}))/sites.txt"


readarray -t URLS < <(cat ${SRC})
selection=$(for URL in "${URLS[@]}"; do echo "$URL"; done | fzf --reverse)

if [ "x${selection}" == "x" ]; then
	echo "[ERROR] nothing selected"
	exit
fi

path=$(echo "${selection}" | cut -d ' ' -f1)
nohup $CMD "${path}" >&/dev/null &

