#! /usr/bin/env bash
# filenme: ff_launch.sh
# 20250605 v2 en

gr_FF=/c/Users/gregor.redelonghi/majstaf_en/majprogs_en/FireFox_63.0.1/FirefoxPortable.exe

SRC="$(dirname $(realpath ${BASH_SOURCE[0]}))/sites.txt"


readarray -t URLS < <(cat ${SRC})
selection=$(for URL in "${URLS[@]}"; do echo "$URL"; done | fzf --reverse)

if [ "x${selection}" == "x" ]; then
	echo "[ERROR] nothing selected"
	exit
fi

path=$(echo "${selection}" | cut -d ' ' -f1)
cygstart $gr_FF "${path}"

